[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/designer"
  to = "/contact.html"
  status = 301

[[redirects]]
  from = "/design"
  to = "/contact.html"
  status = 301

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

# Fallback for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[headers]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
